### ISSUE TITLE
Support for Java 8 and Android Gradle Plugin 3.0.0 

### ISSUE THREAD

**Issue by ngaspama** [vanniktech/gradle-android-junit-jacoco-plugin#100]
After upgrading the android gradle plugin to version 3.0.0 and adding java 8, the jacoco report is NOT generated anymore. Is this an issue with Java 8? If yes, how can get it to generate the report again?

**Comment by vanniktech** [comment]
It should just work. Sadly there's not enough information for me on taking any action here.

**Comment by ngaspama** [comment]
Sorry, for some reasons I wasn't running the correct task to generate the report. It works correctly now.
