### ISSUE TITLE
Instant App Support

### ISSUE THREAD

**Issue by dazza5000** [vanniktech/gradle-android-junit-jacoco-plugin#110]
This plugin doesn't look like it works on Android Instant Apps

**Comment by vanniktech** [comment]
That's true. It's missing a few things [here](https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/blob/ddf89ba2fb72098884be95b8d8a4c95c1f220e92/src/main/groovy/com/vanniktech/android/junit/jacoco/GenerationPlugin.groovy#L291).

[This project](https://github.com/vanniktech/gradle-code-quality-tools-plugin/blob/fa9f32d359a98675076d9f399fdf3e2d98e45272/src/main/groovy/com/vanniktech/code/quality/tools/CodeQualityToolsPlugin.groovy#L356) does check for the other variants.

Mind coming up with a PR to fix that?

**Comment by dazza5000** [comment]
I would be up for it - could you provide some pointers?

Thank you!

Darran

**Comment by vanniktech** [comment]
Yeah it's the first link that I posted and then the second link shows the possible plugin ids.

**Comment by dazza5000** [comment]
Could you give me one more hint of what I should do with those?

**Comment by vanniktech** [comment]
You need to add those checks in here.

**Comment by dazza5000** [comment]
I submitted a pull request. Please let me know if there is anything I need
to include/change.

Darran

**Comment by vanniktech** [comment]
Fixed by #111
