### ISSUE TITLE
Snapshot build is broken

### ISSUE THREAD

**Issue by mtsahakis** [vanniktech/gradle-android-junit-jacoco-plugin#119]
The last couple of days I keep getting: 

"Plugin with id 'com.vanniktech.android.junit.jacoco' not found."

This is how my top level build.gradle file looks like:

buildscript {
    ext.kotlin_version = '1.2.41'
    ext.gradle_plugin = '3.1.2'
    ext.gitflow_plugin = '0.2.0'
    ext.android_junit_jacoco_plugin = '0.12.0-SNAPSHOT'
    ext.sonar_plugin = '2.6.2'
    ext.gradle_git_plugin = '2.2.0'
    repositories {
        jcenter()
        google()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$gradle_plugin"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.github.amkay:gradle-gitflow:$gitflow_plugin"
        classpath "com.vanniktech:gradle-android-junit-jacoco-plugin:$android_junit_jacoco_plugin"
        classpath "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:$sonar_plugin"
        classpath "org.ajoberstar:grgit:$gradle_git_plugin"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
    ext {
        // dependencies versions
        support = "27.1.1"
        googlePlay = "15.0.0"
        roomVersion = "1.1.0"
        testSupport = "1.0.1"
        espresso = "3.0.2"
        constraintLayout = "1.1.0"
        multidex = "1.0.3"
        junit = "4.12"
        mockito = "2.18.3"
        json = "20171018"
        dagger = "2.14.1"
        rxjava = "2.1.12"
        rxandroid = "2.0.1"
        retrofit = "2.3.0"
        evernote = "1.2.5"
        stetho = "1.5.0"
    }

Should I just switch to 0.11.0 release one?

**Comment by mtsahakis** [comment]
Could you test the following configuration:

buildscript {
  repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
  }
  dependencies {
    classpath "com.vanniktech:gradle-android-junit-jacoco-plugin:0.12.0-SNAPSHOT"
  }
}

apply plugin: "com.vanniktech.android.junit.jacoco"

Both on my local machine and on my CI I keep getting 

**Plugin with id 'com.vanniktech.android.junit.jacoco' not found.**

**Comment by vanniktech** [comment]
Huh interesting. Indeed. Will need to investigate.

**Comment by mtsahakis** [comment]
Thanks. For the time being I reverted my builds to 0.11.0 and it looks ok so far.

**Comment by vanniktech** [comment]
@mtsahakis got a fix pending in #120 thank you very much for noticing this. Sorry it took a bit longer to figure out on my side

**Comment by mtsahakis** [comment]
Thanks for picking it up, much obliged. I will move back to SNAPSHOT releases.
