### ISSUE TITLE
Support different flavors / build config for multiple modules with one gradle task

### ISSUE THREAD

**Issue by Chrylo** [vanniktech/gradle-android-junit-jacoco-plugin#123]
Hey, like your description said:

> When having debug & release build types and red & blue flavors the following tasks would be created: jacocoTestReportRedDebug, jacocoTestReportBlueDebug, jacocoTestReportRedRelease and jacocoTestReportBlueRelease.

This introduces the problem, that your build scripts need multiple gradle tasks to generate every report of the project. For example:

```
./gradlew jacocoTestReportBlueDebug
./gradlew jacocoTestReportRedRelease
```

It would be awesome if it had the same behavior as the **assemble** gradle task. For example the following code executes **assembleBlueDebug and assembleRedDebug**:

`./gradlew assembleDebug`

**Comment by vanniktech** [comment]
This should not be a problem if you execute the `check` task. https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/blob/203d027ab744ba812c7c52e0d744142a457130ef/src/main/groovy/com/vanniktech/android/junit/jacoco/GenerationPlugin.groovy#L215

Also there is `jacocoTestReportMerged`.

https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/blob/203d027ab744ba812c7c52e0d744142a457130ef/src/main/groovy/com/vanniktech/android/junit/jacoco/GenerationPlugin.groovy#L244
