### ISSUE TITLE
Why replace $$ with $??

### ISSUE THREAD

**Issue by cgcgbcbc** [vanniktech/gradle-android-junit-jacoco-plugin#13]
https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/blame/master/src/main/groovy/com/vanniktech/android/junit/jacoco/Generation.groovy#L45-L46

Butterknife will generate class whose name include `$$`, thus the class name will be `Fragment$$ViewBinder.class`, for example. Then jacoco will throw exception since class cannot be found.

**Comment by vanniktech** [comment]
@cgcgbcbc I'm currently working on version 0.3.0 and there I'll replace the replacing of `$$`. You can check the snapshot already of it
