### ISSUE TITLE
gradlew task for generating combined result is not showing proper result

### ISSUE THREAD

**Issue by ujwalthote** [vanniktech/gradle-android-junit-jacoco-plugin#138]
When I open generated **index.html** file in **build/reports/jacocoCombined** directory
It shows combined results fine, 
but it shows coverage for all the instrumentation tests 0% 
and coverage for JUnit tests is showing correctly.

One more thing is that when I open **index.html** in **build/reports/coverage** directory which is generated only for **instrumentation tests** is showing correct results, 

why it is not being shown in the report which is generated for combined results?

Point to be added, **includeInstrumentationCoverageInMergedReport**  is also **true**

**Comment by vanniktech** [comment]
@vRallev is this intended?

**Comment by vRallev** [comment]
If you see the coverage for instrumentation tests separately, then this sounds like a bug.

**Comment by ujwalthote** [comment]
Thanks for the update, is there any other way to achieve this?

**Comment by vanniktech** [comment]
Folding this into #139. I think something broke between then and now. Maybe some Android Gradle Plugin upgrade? Gradle? Dunno.
