### ISSUE TITLE
Enhancement: Provide configuration option for CI generated instrumented coverage

### ISSUE THREAD

**Issue by pardom** [vanniktech/gradle-android-junit-jacoco-plugin#144]
Currently to add instrumentation coverage reports generated by Firebase Test Lab, I do the following:

```groovy
tasks.withType(JacocoMerge.class) { task ->
  project.subprojects { subProject ->
    task.executionData += subProject.fileTree(subProject.buildDir).matching {
      include "**/*.ec"
    }
  }
}
```

This is required as combined report tasks depend on the connected check tasks. It would be nice if this were configurable via the extension.

E.g.

```
junitJacoco {
  ...
  combinedDependsOnInstrumentation = true // type boolean
}
```

**Comment by vanniktech** [comment]
I've never used the Firebase Test Lab. Why do we need to include them and if so should not we include them by default?

**Comment by pardom** [comment]
This is not about including anything specific to Firebase Test Lab, that's just a use case. Often the generation of instrumented test reports cannot be done locally. To merge the results of the remotely generated report, we need to add the `.ec` without depending on that task.

**Comment by pavelnazimok** [comment]
I also have this problem. I run instrumented tests remotely in Firebase Test Lab and download the `.ec ` after. So when I want to create combined merged report, I already have the `.ec` and don't need to run instrumented tests again.
(Firebase [docs](https://firebase.google.com/docs/test-lab/android/command-line#running_your_instrumentation_tests) about coverage)

**Comment by vanniktech** [comment]
So the idea is that the task that we add also includes other file formats?

**Comment by vanniktech** [comment]
We do have some code that always adds the files.

https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/blob/master/src/main/groovy/com/vanniktech/android/junit/jacoco/GenerationPlugin.groovy#L239
