### ISSUE TITLE
Why ./gradle build test launch androidConnectedTest task ? 

### ISSUE THREAD

**Issue by aygalinc** [vanniktech/gradle-android-junit-jacoco-plugin#147]
Hi,

I have integrated your plugin in one of my project and i have the following problem.
I develop several  gradle module to build a modular middleware. 
I have a test module that contains an Android app in order to do the integration test of my middleware. Test have different flavor depending on the network layers that my middleware use (Http, Ble, usb...).
At this point, i have a CI environment that build and run test only for http because it can be keep inside the simulator. 

My Ci start to build all modules and unit test them. But when i launch ./gradlew build test, it also triggers androidConnectedHttpTest and androidConnectedBleTest. In my understanding, ./gradlew test must only runs unit test. 

Before I integrate your plugin instrumented tests were not launched. 

So is this a bug or i misunderstand something ? 

I try with plugin in version 0.13 & 0.14.0-SNAPSHOT, Gradle in 4.10.2 & android build tools in 3.3.0.

**Comment by vanniktech** [comment]
I think it's because of https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/blob/b72e78b6e22d11c19b75bddd7e04abf7aff3383a/src/main/groovy/com/vanniktech/android/junit/jacoco/GenerationPlugin.groovy#L97

**Comment by aygalinc** [comment]
The project has com.android.application plugin, so normally  : 

`   if (isAndroidProject(subProject)) {
                return addJacocoAndroid(subProject, extension, mergeTask, mergedReportTask)
            } else if (isJavaProject(subProject)) {
                return addJacocoJava(subProject, extension, mergeTask, mergedReportTask)
}`

will go in addJacocoAndroid and so cannot fall to line 97 which is in AddJacocoJava no ?

**Comment by vanniktech** [comment]
Ah right. Dunno your project but it does seem weird. Can you debug who's calling `androidConnectedTest` and why?

**Comment by aygalinc** [comment]
Maybe it is due to line 256 : 

subProject.check.dependsOn "${taskName}"

For android project plugin generates 2 tasks if enableCoverageFlag is true : jacocoTestReport and combinedTestReport. Both are linked to check task.

**Comment by aygalinc** [comment]
Maybe a : 
if (combined) {
         subProject.check.dependsOn "${taskName}"
        } else {
            subProject.test.dependsOn "${taskName}"
        }

will solve it ?

**Comment by vanniktech** [comment]
> subProject.check.dependsOn "${taskName}"

Sounds promising yeah. Although I like the behavior. Why do you want to change it?

**Comment by aygalinc** [comment]
Sorry i confused connectedCheck and check. 

The thing that i don't understand is : 
-> ./gradlew  test : it launch Unit test and connectedAndroidTest
tests:base.service.test:connectedCoapUsbDebugAndroidTest
-> ./gradlew :tests:base.service.test:test launch only Unit Test 

How can i proceed to debug who is calling connectedAndroidTest ?

**Comment by vanniktech** [comment]
I think Gradle can help you with that. I'd need to look into it myself but I don't have the time currently

**Comment by aygalinc** [comment]
I just do a quick test by replacing at line 22
` addJacoco(subProject, extension, mergeTask, mergedReportTask) ` by `          addJacoco(subProject, extension)` and the androidCheckTask is no more trigger...

**Comment by aygalinc** [comment]
After changing lot of things , the error vanishes. So i think it was probably my fault.

**Comment by vanniktech** [comment]
Sweet!
