### ISSUE TITLE
jacoco.includeNoLocationClasses for instrumentation test change

### ISSUE THREAD

**Issue by aygalinc** [vanniktech/gradle-android-junit-jacoco-plugin#148]
Hi,

As explained here : https://veskoiliev.com/how-to-setup-jacoco-for-android-project-with-java-kotlin-and-multiple-flavours/ , android Dsl syntax as change in version 3.3.0 and so the valid way to configure this is now : 

tasks.withType(Test) {
    jacoco.includeNoLocationClasses = true
}

**Comment by vanniktech** [comment]
Mind creating a PR for that?

**Comment by vanniktech** [comment]
Thanks for your PR in #150

I've merged it

**Comment by grndvl1** [comment]
Where is this flag for Kotlin DSL. 

```
tasks.withType<Test> {
    useJUnitPlatform()
//              this option is not available
    jacoco.includeNoLocationClasses = true.
}

```
