### ISSUE TITLE
After gradle 5.1.1 upgrade, "mergeJacocoReports" task is failing in multi module project

### ISSUE THREAD

**Issue by vasdeepika** [vanniktech/gradle-android-junit-jacoco-plugin#156]
Hi,
We have multi module project.  I am using the latest released version(0.14.0) of this plugin. When I run mergeJacocoReports task then build is failing with the below error:
No signature of method: org.gradle.api.internal.file.CompositeFileCollection$1.setFrom() is applicable for argument types: (ArrayList) values: [[/Users/xxx/build/jacoco/testDebugUnitTest.exec]]

If I change realExecutionData assignment in mergeTask then it works fine
**Existing code**:
doFirst {
                // Filter non existing files.
                def realExecutionData = project.files().asFileTree
                .....

**Modified code**:
 doFirst {
                // Filter non existing files.
                def realExecutionData = project.files()
                .....
Can you look into this and let me know why this is failing for me?

Thanks!

**Comment by vanniktech** [comment]
Huh interesting. Can you try out 0.15.0-SNAPSHOT?

The code change to do is probably safe to do. Wondering why it's failing though. Which version of Gradle were you running before?

**Comment by vasdeepika** [comment]
Thanks for the quick response! Seeing the same error in 0.15.0-SNAPSHOT too.  Before I was using 4.10.1 version of Gradle.

**Comment by vanniktech** [comment]
Do you mind creating a PR with your fix? I can merge and then it'll be fixed in the new version.

**Comment by vasdeepika** [comment]
PR is open.  Please merge it when you have time.

**Comment by vanniktech** [comment]
Thank you. Fixed by #157

**Comment by howtimeflies-io** [comment]
Hi @vanniktech, could you please make a new release for this fix? Thank you.
