### ISSUE TITLE
org.gradle.process.internal.ExecException

### ISSUE THREAD

**Issue by igorwojda** [vanniktech/gradle-android-junit-jacoco-plugin#161]
I am experiencing an issue where after [enabling the plugin](https://github.com/igorwojda/android-showcase/commit/8da4e2ec149e2d20dc76ab3667f2846b93c6b0e6) circle ci build fails for `./gradlew testDebugUnitTest` command
https://circleci.com/gh/igorwojda/android-showcase/1694

Locally I can run `./gradlew testDebugUnitTest` just fine 🤔

You can observe the issue on [jacoco-plugin-dependency](https://github.com/igorwojda/android-showcase/tree/jacoco-plugin-dependency) branch

**Comment by vanniktech** [comment]
Seems like you should report this over at Gradle since I'm only using their things.
