### ISSUE TITLE
Android Gradle Plugin 3.5 breaks configuration

### ISSUE THREAD

**Issue by mattinger** [vanniktech/gradle-android-junit-jacoco-plugin#162]
Due to apparent change in the the location of where compiled classes go, this plugin no longer works with android plugin version 3.5.

Classes now appear in `intermediates/javac/debug/classes`

**Comment by vanniktech** [comment]
Want to submit a PR to fix this?

**Comment by yaizudamashii** [comment]
It seems that you fixed the problem @mattinger mentioned in the snapshot.  Thank you. 
I found another issue with android plugin version 3.5 with gradle 5.4.  
```
"**/intermediates/javac/${sourceName}/*/classes/**" // Android Gradle Plugin 3.2.x support.
```
seems to produce no files to refer to.  It was necessary for me to use
```
"**/intermediates/javac/${buildFlavor}/classes/**",
```

**Comment by eugenio1590** [comment]
I suppose that broke the `junitJacoco` extension. Any progress on this?

**Comment by damiancioo** [comment]
I have 0.15 plugin version with build.gradle.kts
`
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath(LibraryDependency.JACOCO_PLUGIN)
    }
}
apply {
    plugin(GradlePluginId.JACOCO_PLUGIN)
}
`
After that Android Studio doesn't seems to allow to configure 'junitJacoco'. 
Is this related to this or kts?
