### ISSUE TITLE
Support android dynamic features (Release 0.16.0?)

### ISSUE THREAD

**Issue by VMadalin** [vanniktech/gradle-android-junit-jacoco-plugin#164]
First of all, thank you for this plugin and for the maintenance that you give it.  When you plan to release a new version to include this merged PR  https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/pull/158 (thanks to @igorwojda ) and another merged changes, allow us to use this awesome `jacoco` plugin with `dynamic features` ?. 

For all who are in the same situation, please use this workaround to add directly the master branch as project dependency, until the new version will release that includes these changes.

```
buildscript {
  repositories {
    mavenCentral()
    maven { url "https://jitpack.io" }
  }
  dependencies {
    classpath "com.github.vanniktech:gradle-android-junit-jacoco-plugin:master"
  }
}

apply plugin: "com.vanniktech.android.junit.jacoco"
```

or

``` 
buildscript {
  repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
  }
  dependencies {
    classpath "com.vanniktech:gradle-android-junit-jacoco-plugin:0.16.0-SNAPSHOT"
  }
}

apply plugin: "com.vanniktech.android.junit.jacoco"
```

**Comment by vanniktech** [comment]
Sorry this took longer - https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/releases/tag/0.16.0
