### ISSUE TITLE
combinedTestReport doesn't use coverage files from androidTests

### ISSUE THREAD

**Issue by VysotskiVadim** [vanniktech/gradle-android-junit-jacoco-plugin#167]
Currently plugin setups code coverage report files at configuration phase, see **1** at the diagram.
The issue is that for Android Tests we don't know in advance names of code coverage reports files downloaded from a device, because they are available only after tests run, see **2** at the diagram.
![jacoco-plugin-bug](https://user-images.githubusercontent.com/6190346/75545565-aec3f380-5a37-11ea-8169-eaa176b8f215.png)

For my project I fixed the issue by moving the configuration of code coverage files location at stage **3**.

**Comment by vanniktech** [comment]
Thanks for your contribution. Try out the 0.17.0-SNAPSHOT which should be available soon.

**Comment by ardevd** [comment]
Im still seeing this issue on 0.17.0-SNAPSHOT I think. Sometimes the instrumented tests are included in the combined test report, but sometimes it isnt.
