### ISSUE TITLE
Exclude did not work

### ISSUE THREAD

**Issue by franrx** [vanniktech/gradle-android-junit-jacoco-plugin#170]
I'm trying to exclude my model and view classes from coverage report and it didn't work.

Here is my configuration.

junitJacoco {
    jacocoVersion = '0.8.5' // type String
    ignoreProjects = ['data', 'domain', 'profilelibrary', 'app'] // type String array
    excludes = [
            '**/R.class',
            '**/R$*.class',
            '**/*$ViewInjector*.*',
            '**/*$ViewBinder*.*',
            '**/BuildConfig.*',
            '**/Manifest*.*',
            '**/*$Mapper.*',
            '**/*$View.*',
    ]// type String List
    includeNoLocationClasses = false // type boolean
    includeInstrumentationCoverageInMergedReport = false // type boolean
}

**Comment by vanniktech** [comment]
We're just delegating and using what Gradle provides us. So either file there or ask on Stackoverflow.
