### ISSUE TITLE
Defaults for `excludes` should be obvious and additive.

### ISSUE THREAD

**Issue by gtcompscientist** [vanniktech/gradle-android-junit-jacoco-plugin#172]
https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/blob/feb9fa425951617caebe453d5661c9c655146004/src/main/groovy/com/vanniktech/android/junit/jacoco/GenerationPlugin.groovy#L325

Moving the defaults to the Extension allows people to use `=` and `+=` depending on what they'd like to do within their project. Otherwise, you have to copy/paste the defaults to any project that has _additional_ excludes.

**Comment by gtcompscientist** [comment]
Fixed in 0.17

**Comment by twyatt** [comment]
Are there any plans to release 0.17.x?

**Comment by vanniktech** [comment]
Not really, this project needs someone who will maintain it.

**Comment by twyatt** [comment]
> Are there any plans to release 0.17.x?

Just happened to notice that there are some unreleased changes that would be nice to have.

> Not really, this project needs someone who will maintain it.

Totally understand.
Unfortunately, I don't have the free time to offer to help in that regard. 😢
