### ISSUE TITLE
is not excluding java classes from the list in excludes

### ISSUE THREAD

**Issue by mdAlvarenga** [vanniktech/gradle-android-junit-jacoco-plugin#175]
Hello!
first thanks for this plugin that many of us use.

I am having a problem excluding classes or packages from coverage analysis.
That is the code I use to configure exclusions, but it doesn't work for me. Could you help me with this? Is it something that already happened to you?
As I saw the code tests, it should work the way I'm using it, but it's not working for me.

I'm not sure it's an valid Issue, but I upload it this way because maybe it can be.

I would appreciate any help in that regard!

```
junitJacoco {
    jacocoVersion = '0.8.3' // type String
    ignoreProjects = [] // type String array
    excludes = ['**/controllers/AddressController.java']// type String List
OR    excludes = ['**/controllers/AddressController.*]// type String List
OR    excludes = ['**/controllers/*]// type String List
OR any other variant of the string
    includeNoLocationClasses = false // type boolean
    includeInstrumentationCoverageInMergedReport = false // type boolean
}
```

**Comment by vanniktech** [comment]
We're just delegating to whatever the Gradle API offerr's us. If there's a problem, file/ask there.
