### ISSUE TITLE
Disable combinedReport

### ISSUE THREAD

**Issue by S-Dutta1** [vanniktech/gradle-android-junit-jacoco-plugin#180]
On applying the plugin to my gradle script and running gradle build, the combinedReport tasks automatically run the instrumentation tests. Is there a way to disable this, so that I can later separately run the combinedReport tasks ?

**Comment by vanniktech** [comment]
Yeah just use the Gradle syntax. `tasks.named("combinedReport")` and then there's a disable property or something like that.
