### ISSUE TITLE
jacocoTestReportMerged is not generated in my app which has product flavor

### ISSUE THREAD

**Issue by gkaradagan** [vanniktech/gradle-android-junit-jacoco-plugin#182]
Hi,
I just want to get report of all my feature modules. And my modules haven't aware of flavor. Flavor is exist in only app. So i run  jacocoTestReportDebug and it generates all reports separately but i want to combine all of them. But my issue is jacocoTestReportMerged not generated.

./gradlew jacocoTestReportDebug jacocoTestReportMerged

* What went wrong:
Task 'jacocoTestReportMerged' not found in root project

**Comment by vanniktech** [comment]
As far as I can recall, I've never really supported flavors here.
