### ISSUE TITLE
Unable to exclude java methods contains lambda expression using Jacoco

### ISSUE THREAD

**Issue by ajay4dhurvanshi** [vanniktech/gradle-android-junit-jacoco-plugin#188]
Hi Team,

I want to exclude some of the java methods from getting covered in the JaCoCo report.

I tried with @lombok.Generated annotation it is ignoring the method but if there are any java8 features(like lambda expression) in those methods, it is not able to ignore those lines and still showing some coverage for those lines.

Is there any other configuration or way to exclude the whole method from the Jacoco report even if it is using some java8 code?
    
Thanks in Advance.

**Comment by vanniktech** [comment]
Not that I know. Best to ask at stackoverflow.com
