### ISSUE TITLE
GrapeJuice

### ISSUE THREAD

**Issue by deepankarb** [vanniktech/gradle-android-junit-jacoco-plugin#202]
Hi,

Thanks for this awesome plugin! 

The name is too literal and IMHO it would benefit greatly e.g. in discussions and maintenance/code readability to give a name to the plugin. I suggest: GrapeJuice (**GR**adle **A**ndroid **P**lugin **JU**nit Jacoco) - it's a leap but I think anything else would also work as long as it's distinct and a name, not a description :)

Thanks again!

**Comment by vanniktech** [comment]
Sounds good to me, although this project is more in a need of a person who will maintain it.

**Comment by vanniktech** [comment]
Let's leave it
