### ISSUE TITLE
Plugin execution fails if build flavors are configured

### ISSUE THREAD

**Issue by nohum** [vanniktech/gradle-android-junit-jacoco-plugin#28]
Suppose the following configuration (root `build.gradle`):
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
        mavenLocal()
        maven {
            url "https://oss.sonatype.org/service/local/repositories/snapshots/content" // needed for jacoco snapshot plugin
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0-alpha5'
        classpath 'com.vanniktech:gradle-android-junit-jacoco-plugin:0.4.0-SNAPSHOT'
    }
}

allprojects {
    repositories {
        jcenter()
        mavenLocal()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

Now I have a single subproject called `app` which includes your latest `0.4.0-SNAPSHOT` version as seen above like needed via `apply plugin: "com.vanniktech.android.junit.jacoco"` but also posses some build flavors. This is the shortened `build.gradle`file:

```
apply plugin: 'com.android.application'
apply plugin: "com.vanniktech.android.junit.jacoco"

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    buildTypes {
        release {
        debug
    }

    flavorDimensions "target"

    productFlavors {
        staging {
            dimension "target"
        }
        live {
            dimension "target"
        }
    }
}
```

Because of this configuration, there is no `testDebugUnitTest` task, but rather there are tasks for `testStagingDebugUnitTest` and `testLiveDebugUnitTest`, one for each flavor. Because of this, calling `gradle jacocoTestReportDebug` on the root project fails as follows:

```
% gradle jacocoTestReportDebug

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:jacocoTestReportDebug'.
> Task with path 'testDebugUnitTest' not found in project ':app'.
```

The plugin should correctly create a task for each flavor like `jacocoTestReportStagingDebug` and `jacocoTestReportLiveDebug` or take care somehow other of that issue.

**Comment by vanniktech** [comment]
@nohum flavors are not yet supported. Simply because I don't use them in my projects. Feel free to contribute this feature in here. As a starting point have a look [here](https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/blob/6e3b0e58d133bc568421375a77a945f546d0719b/src/main/groovy/com/vanniktech/android/junit/jacoco/Generation.groovy#L87) where I collect the `buildTypes` but not the flavors

**Comment by vanniktech** [comment]
@nohum: @outlying PR got merged and for now you can use the SNAPSHOT. I'll try to cut a release in the next few days.

**Comment by vanniktech** [comment]
@nohum @outlying version 0.5.0 has been released

**Comment by tmehta813** [comment]
still having this issue on 0.8.5
