### ISSUE TITLE
Coverage only for unit tests in Android projects

### ISSUE THREAD

**Issue by outlying** [vanniktech/gradle-android-junit-jacoco-plugin#35]
Currently, code is skipping all Android tests since Jacoco tasks are based on `test${sourceName.capitalize()}UnitTest`

I'm not sure if this is intended or not, but further, in code plugin ignores a lot of Android related stuff

    private static ArrayList<String> getExcludes() {
        ['**/R.class',
         '**/R$*.class',
         '**/*$$*',
         '**/*$ViewInjector*.*',
         '**/*$ViewBinder*.*',
         '**/BuildConfig.*',
         '**/Manifest*.*',
         '**/*$Lambda$*.*', // Jacoco can not handle several "$" in class name.
         '**/*Dagger*.*', // Dagger auto-generated code.
         '**/*MembersInjector*.*', // Dagger auto-generated code.
         '**/*_Provide*Factory*.*' // Dagger auto-generated code.
        ]
    }

This suggests that coverage should include instrumentation tests as well

**Comment by vanniktech** [comment]
Yes this is wanted that those things are ignored. I also want to provide an extension so consumers of this library can customize it.

AFAIK Android Studio Plugin will generate you Jacoco reports when you are using Instrumentation tests. You need to set `testCoverageEnabled true` or something alike.

**Comment by outlying** [comment]
OK

**Comment by vanniktech** [comment]
@outlying version 0.5.0 has been released with an option to overwrite the default excludes
