### ISSUE TITLE
Test report has created ,but coverage report not.

### ISSUE THREAD

**Issue by songzhiy** [vanniktech/gradle-android-junit-jacoco-plugin#44]
I run gradlew jacocoTestReportDebug ,test report has create,but jacoco's coverage report not.
What's the matter? Is my build.gradle config error? Or command error?
My project is Android Project and I add config in the root build.gradle .

**Comment by vanniktech** [comment]
Need a little bit more information than that

**Comment by songzhiy** [comment]
This is my root/build.gradle 
`// Top-level build file where you can add configuration options common to all sub-projects/modules.
apply plugin: 'com.vanniktech.android.junit.jacoco'

buildscript {
    repositories {
        jcenter()
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.3'
        classpath 'com.vanniktech:gradle-android-junit-jacoco-plugin:0.5.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`
My project have my defined lint issue and have 2 failure test case .
This is I ran gradlew jacocoTestReportDebug

`D:\Project\gitlab_ci_test_pro>gradlew jacocoTestReportDebug
Incremental java compilation is an incubating feature.                                     
lint do lint_aar gradle                                                                                                                                         
:app:preBuild UP-TO-DATE    
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:lint_aar:preBuild UP-TO-DATE
:lint_aar:preReleaseBuild UP-TO-DATE
:lint_aar:compileReleaseNdk UP-TO-DATE
:szy_lint:compileJava                                                                      
:szy_lint:processResources UP-TO-DATE
:szy_lint:classes
:szy_lint:jar
:lint_aar:copyLintJar
:lint_aar:compileLint
:lint_aar:copyReleaseLint                 
:lint_aar:checkReleaseManifest
:lint_aar:preDebugAndroidTestBuild UP-TO-DATE
:lint_aar:preDebugBuild UP-TO-DATE
:lint_aar:preDebugUnitTestBuild UP-TO-DATE
:lint_aar:preReleaseUnitTestBuild UP-TO-DATE
:lint_aar:prepareComAndroidSupportAnimatedVectorDrawable2340Library
:lint_aar:prepareComAndroidSupportAppcompatV72340Library                 
:lint_aar:prepareComAndroidSupportSupportV42340Library                 
:lint_aar:prepareComAndroidSupportSupportVectorDrawable2340Library
:lint_aar:prepareReleaseDependencies
:lint_aar:compileReleaseAidl
:lint_aar:compileReleaseRenderscript                 
:lint_aar:generateReleaseBuildConfig
:lint_aar:mergeReleaseShaders                 
:lint_aar:compileReleaseShaders
:lint_aar:generateReleaseAssets
:lint_aar:mergeReleaseAssets
:lint_aar:generateReleaseResValues UP-TO-DATE
:lint_aar:generateReleaseResources
:lint_aar:mergeReleaseResources                 
:lint_aar:processReleaseManifest                 
:lint_aar:processReleaseResources                 
:lint_aar:generateReleaseSources
:lint_aar:incrementalReleaseJavaCompilationSafeguard
:lint_aar:compileReleaseJavaWithJavac                 
:lint_aar:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:lint_aar:extractReleaseAnnotations                   
:lint_aar:mergeReleaseProguardFiles UP-TO-DATE
:lint_aar:packageReleaseRenderscript UP-TO-DATE
:lint_aar:packageReleaseResources
:lint_aar:processReleaseJavaRes UP-TO-DATE
:lint_aar:transformResourcesWithMergeJavaResForRelease
:lint_aar:transformClassesAndResourcesWithSyncLibJarsForRelease                 
:lint_aar:mergeReleaseJniLibFolders
:lint_aar:transformNative_libsWithMergeJniLibsForRelease
:lint_aar:transformNative_libsWithSyncJniLibsForRelease
:lint_aar:bundleRelease
:app:prepareComAndroidSupportAnimatedVectorDrawable2340Library                 
:app:prepareComAndroidSupportAppcompatV72340Library                 
:app:prepareComAndroidSupportSupportV42340Library                 
:app:prepareComAndroidSupportSupportVectorDrawable2340Library
:app:prepareGitlab_ci_test_proLint_aarUnspecifiedLibrary
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript                 
:app:generateDebugBuildConfig
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:app:mergeDebugAssets                 
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources
:app:mergeDebugResources                 
:app:processDebugManifest
:app:processDebugResources                 
:app:generateDebugSources
:app:incrementalDebugJavaCompilationSafeguard
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:app:incrementalDebugUnitTestJavaCompilationSafeguard UP-TO-DATE
:app:preDebugUnitTestBuild UP-TO-DATE
:app:prepareDebugUnitTestDependencies
:app:compileDebugUnitTestJavaWithJavac
:app:compileDebugUnitTestJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:app:processDebugJavaRes UP-TO-DATE                    
:app:processDebugUnitTestJavaRes UP-TO-DATE
:app:compileDebugUnitTestSources
:app:mockableAndroidJar                 
:app:assembleDebugUnitTest
:app:testDebugUnitTest                                     

com.szy.gitlab_ci.ExampleUnitTest > addition_isCorrect FAILED
    java.lang.AssertionError at ExampleUnitTest.java:13

com.szy.gitlab_ci.test.TestBeanTest > testErrorAddAll FAILED
    java.lang.AssertionError at TestBeanTest.java:21

3 tests completed, 2 failed
:app:testDebugUnitTest FAILED          

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:testDebugUnitTest'.
> There were failing tests. See the report at: file:///D:/Project/gitlab_ci_test_pro/app/build/reports/tests/debug/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 35.809 secs
`

Then I open app/build/report directory , only have test directory. It contains junit test case .But jacoco report not in it .

**Comment by vanniktech** [comment]
I think because the unit tests failed the report was not generated. Also I formatted your post and correct the usage of `

**Comment by songzhiy** [comment]
Yes. When I close test case which failed , the report created. All test case are success is the permission of creating the jacoco report? Is this so strict ?

**Comment by vanniktech** [comment]
Yup I think that's a limitation of Jacoco though and not of this plugin.

**Comment by vanniktech** [comment]
I'll close this feel free to open a new issue if you have any more questions.
