### ISSUE TITLE
Is this work for gitlab?

### ISSUE THREAD

**Issue by gengjiawen** [vanniktech/gradle-android-junit-jacoco-plugin#45]
I tried in gitlab,But coverage status is still unknown.

**Comment by vanniktech** [comment]
Never used gitlab and this only generates jacoco reports so don't know what you're expecting from this.

**Comment by gengjiawen** [comment]
I am expecting something like codecov(like this project) and coverage to show the project test statistic. I will try others ways.Thanks :)

**Comment by vanniktech** [comment]
Codecov requires a Jacoco file which this plugin generates. It does nothing other than that. Posting the coverage to the PRs and providing an overall coverage is done by Codecov

**Comment by gengjiawen** [comment]
yes, the coverage report in gitlab need to config in `.gitlab-ci.yml`, So I need to dig in a little more.
