### ISSUE TITLE
Use jacoco version 0.7.7 to be compatible to jenkins plugin

### ISSUE THREAD

**Issue by tilmanginzel** [vanniktech/gradle-android-junit-jacoco-plugin#46]
Hey,

we use this plugin in combination with the [JaCoCo Jenkins Plugin](https://wiki.jenkins-ci.org/display/JENKINS/JaCoCo+Plugin) to show a coverage report trend in the jenkins build. While searching for a reason why the code coverage reports in Jenkins are empty, I found the following issue: https://issues.jenkins-ci.org/browse/JENKINS-28652

> Unfortunately JaCoCo 0.7.5 breaks compatibility to previous binary formats of the jacoco.exec files. The JaCoCo plugin up to version 1.0.19 is based on JaCoCo 0.7.4, thus you cannot use this version with projects which already use JaCoCo 0.7.5 or newer. JaCoCo plugin starting with version 2.0.0 uses JaCoCo 0.7.5 and thus requires also this version to be used in your projects. Please stick to JaCoCo plugin 1.0.19 or lower if you still use JaCoCo 0.7.4 or lower

This gradle plugin still uses an old JaCoCo version 0.7.2 as a default. So to improve the compatibility (without having to configure it manually), I updated the version to the latest version '0.7.7.201606060606'. Are there any objections about this change?

**Comment by vanniktech** [comment]
It's [configurable](https://github.com/vanniktech/gradle-android-junit-jacoco-plugin#configuration) so there's no need to increase the default version

**Comment by tilmanginzel** [comment]
I see no reason to not update it, because it could save some time for people who face the issue above. But it's not necessary of course, your decision. :)

**Comment by vanniktech** [comment]
Since in order to make this change effective a new version of the plugin would need to be pushed and everyone would need to update too, so I'll close this as the version can already be configured. Also I don't feel like making a new version with just this change, if people want a different version of JaCoCo they can achieve this already.

**Comment by tilmanginzel** [comment]
Alright, no problem. ;)

**Comment by vanniktech** [comment]
Thanks for the PR / issue though
