### ISSUE TITLE
Flavor Dimensions not supported

### ISSUE THREAD

**Issue by jaredsburrows** [vanniktech/gradle-android-junit-jacoco-plugin#50]
https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/blob/master/src/main/groovy/com/vanniktech/android/junit/jacoco/Generation.groovy#L93

It looks like you may need to iterate over the "variants" in order to pick up the flavor dimensions.

**Comment by vanniktech** [comment]
According to the tests it does work. Also I don't use Flavors in any apps so I would not notice. Is this just an assumption?

**Comment by jaredsburrows** [comment]
It supports Flavors and Buildtypes but not flavor dimensions. Iterating over "variants" like in your APK plugin will automatically support it: https://github.com/vanniktech/gradle-android-apk-size-plugin/blob/master/src/main/groovy/com/vanniktech/android/apk/size/ApkSizePlugin.groovy#L21.

**Comment by vanniktech** [comment]
Oh yes now I get what you mean. Those I'm not using either. PR welcome but I won't add it.

**Comment by passsy** [comment]
should be also fixed with #69

**Comment by vanniktech** [comment]
Can you double check @jaredsburrows ?

**Comment by passsy** [comment]
just tested it with:
`classpath 'com.vanniktech:gradle-android-junit-jacoco-plugin:0.7.0-20170711.160954-3'`

```
    flavorDimensions 'audience', 'payed'

    productFlavors {
        dev {
            dimension 'audience'
        }

        beta {
            dimension 'audience'
        }

        play {
            dimension 'audience'
        }

        payed {
            dimension 'payed'
        }

        free {
            dimension 'payed'
        }
    }
```

produces:

```
Reporting tasks
---------------
jacocoTestReportBetaFreeDebug - Generate Jacoco coverage reports after running betaFreeDebug tests.
jacocoTestReportBetaFreeRelease - Generate Jacoco coverage reports after running betaFreeRelease tests.
jacocoTestReportBetaPayedDebug - Generate Jacoco coverage reports after running betaPayedDebug tests.
jacocoTestReportBetaPayedRelease - Generate Jacoco coverage reports after running betaPayedRelease tests.
jacocoTestReportDevFreeDebug - Generate Jacoco coverage reports after running devFreeDebug tests.
jacocoTestReportDevFreeRelease - Generate Jacoco coverage reports after running devFreeRelease tests.
jacocoTestReportDevPayedDebug - Generate Jacoco coverage reports after running devPayedDebug tests.
jacocoTestReportDevPayedRelease - Generate Jacoco coverage reports after running devPayedRelease tests.
jacocoTestReportPlayFreeDebug - Generate Jacoco coverage reports after running playFreeDebug tests.
jacocoTestReportPlayFreeRelease - Generate Jacoco coverage reports after running playFreeRelease tests.
jacocoTestReportPlayPayedDebug - Generate Jacoco coverage reports after running playPayedDebug tests.
jacocoTestReportPlayPayedRelease - Generate Jacoco coverage reports after running playPayedRelease tests.
```

🎉

**Comment by jaredsburrows** [comment]
Great. I'll add a unit test for this or maybe you can? Thanks for fixing
this!

**Comment by vanniktech** [comment]
Won't have that much time on adding a unit test for this (maybe there's already one?) but yes a unit test for this would be awesome. I'll then in the next few days publish a new version with the support for this.

**Comment by passsy** [comment]
There is not much to test what's not already tested. The android gradle plugin generates the variants for us, we just consume the list. It doesn't make a difference if we get `beta` or `betaPayed` as `productFlavor` name.

**Comment by jaredsburrows** [comment]
@vanniktech @vanniktech I added some tests here: https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/pull/71

**Comment by jaredsburrows** [comment]
I am closing this because the tasks are generated.

**Comment by sametAkdeniz** [comment]
Links are gone, so the solution is not visible anymore.
