### ISSUE TITLE
Fix broken code cov

### ISSUE THREAD

**Issue by jaredsburrows** [vanniktech/gradle-android-junit-jacoco-plugin#72]
CodeCov has not been updated in months:
https://codecov.io/gh/vanniktech/gradle-android-junit-jacoco-plugin/commits

See the latest CI build:
https://travis-ci.org/vanniktech/gradle-android-junit-jacoco-plugin#L364

```
    Executing gcov (find /home/travis/build/[secure]/gradle-android-junit-jacoco-plugin -type f -name '*.gcno'  -exec gcov -pb  {} +)
==> Collecting reports
Error: No coverage report found
Tip: See an example jdk repo: https://github.com/codecov/example-jdk
Support channels:
  Email:   hello@codecov.io
  IRC:     #codecov
  Gitter:  https://gitter.im/codecov/support
  Twitter: @codecov
Done. Your build exited with 0.
```

**Comment by vanniktech** [comment]
Yeah. It just suddenly stopped working.

**Comment by jaredsburrows** [comment]
Time to switch to coveralls?

`gradlew build jacocoTestReport coveralls`
Source: https://github.com/jaredsburrows/gradle-license-plugin/blob/master/.travis.yml#L9

```
coveralls {
  jacocoReportPath = "${buildDir}/reports/jacoco/test/jacocoTestReport.xml"
}
```
Source: https://github.com/jaredsburrows/gradle-license-plugin/blob/master/gradle/quality.gradle#L9

I can make a PR, but you have to set it up at coveralls.io.

**Comment by vanniktech** [comment]
Yup let's switch if it's easier and has the same functionality.

**Comment by jaredsburrows** [comment]
@vanniktech Let me know when you have set this repo up with coveralls.io, I can make a PR for the rest.

**Comment by vanniktech** [comment]
Should be active now:

<img width="762" alt="screen shot 2017-07-30 at 13 34 52" src="https://user-images.githubusercontent.com/5759366/28752984-e3216318-752b-11e7-880a-4b460fc5cd85.png">

**Comment by vanniktech** [comment]
Seems to work now does not it? At least I'm seeing stuff [here](https://codecov.io/github/vanniktech/gradle-android-junit-jacoco-plugin?branch=master)

**Comment by jaredsburrows** [comment]
It is weird that it says only 1 file? https://codecov.io/github/vanniktech/gradle-android-junit-jacoco-plugin?branch=master

**Comment by vanniktech** [comment]
True, I'll try deleting the codecov configuration file.

**Comment by jaredsburrows** [comment]
Any luck?

Jared Burrows

*jaredsburrows@gmail.com <jaredsburrows@gmail.com>*
LinkedIn: https://www.linkedin.com/in/jaredsburrows

**Comment by vanniktech** [comment]
According to [this](https://codecov.io/gh/vanniktech/gradle-android-junit-jacoco-plugin/commits) it seems like it broke with Gradle 4.0

**Comment by vanniktech** [comment]
I'm pretty sure I found the reason now. After travis run the SNAPSHOT was built and then `codecov` was executed. Building the SNAPSHOT with `clean uploadArchives` the previously generated reports with `clean build` were deleted and hence `codecov` didn't do anything. I'd expect it to fail but it went silent.  ¯\_(ツ)_/¯

If you look at the travis logs in #78 you can see that the report was uploaded successfully.

**Comment by jaredsburrows** [comment]
Fixed by #78.

**Comment by jaredsburrows** [comment]
@vanniktech It still looks broken here: https://codecov.io/gh/vanniktech/gradle-android-junit-jacoco-plugin

**Comment by vanniktech** [comment]
Yeah I contacted the support team.

**Comment by vanniktech** [comment]
I'm super confused. It seems like codecov works on every android project but not on groovy gradle plugins or java libraries.

- [Working with Android library that also has Gradle 4.1](https://github.com/vanniktech/RxPermission/commits/master)
- [Not working with Java Library with Gradle 4.1](https://github.com/vanniktech/junit-rules/commits/master)
- [Not working with Groovy Gradle Plugins](https://github.com/vanniktech/gradle-android-junit-jacoco-plugin)

Also wrote in https://github.com/codecov/support/issues/374 but no response yet :(

**Comment by jaredsburrows** [comment]
Its time to switch to Coveralls :)

**Comment by vanniktech** [comment]
Do they also give you a summary for each PR?

**Comment by jaredsburrows** [comment]
Yes. Here is an example: https://coveralls.io/github/jaredsburrows/android-gif-example?branch=master.

**Comment by vanniktech** [comment]
But on the PR itself right?

**Comment by jaredsburrows** [comment]
Yes. They are listed in that link. And it posts on the PR itself: https://github.com/jaredsburrows/android-gif-example/pull/22#issuecomment-319588297.

**Comment by vanniktech** [comment]
Awesome then let's switch.

**Comment by vanniktech** [comment]
Starting to think there's something in the generated report wrong. Coveralls also doesn't work - https://coveralls.io/github/vanniktech/gradle-android-junit-jacoco-plugin?branch=master

**Comment by jaredsburrows** [comment]
@vanniktech I believe you are right: 
```
$ cat build/reports/jacoco/test/jacocoTestReport.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><!DOCTYPE report PUBLIC "-//JACOCO//DTD Report 1.0//EN" "report.dtd"><report name="gradle-android-junit-jacoco-plugin"><sessioninfo id="s-MacBook-Pro.local-ed1f7c4f" start="1501540174380" dump="1501540183452"/><sessioninfo id="s-MBP.jetpack-b2b8c50e" start="1501634088702" dump="1501634097753"/><sessioninfo id="s-MBP.jetpack-747de4c" start="1501634170853" dump="1501634179070"/><sessioninfo id="s-MBP.jetpack-1f33f093" start="1501634182345" dump="1501634191147"/><sessioninfo id="s-MBP.jetpack-cf467f29" start="1501634256252" dump="1501634264563"/><sessioninfo id="s-MBP.jetpack-84c59f09" start="1501634311170" dump="1501634319355"/><sessioninfo id="s-MBP.jetpack-cc0bfde" start="1501634340744" dump="1501634349093"/><sessioninfo id="s-MBP.jetpack-cc5c9609" start="1501634442746" dump="1501634451049"/><sessioninfo id="s-MBP.jetpack-9cd95ba9" start="1501634504741" dump="1501634513139"/><sessioninfo id="s-MBP.jetpack-fbfb186f" start="1501634589073" dump="1501634597405"/><sessioninfo id="s-MBP.jetpack-6982b093" start="1501634909817" dump="1501634918335"/><sessioninfo id="s-MBP.jetpack-96834cd9" start="1501634927543" dump="1501634936383"/><sessioninfo id="s-MBP.jetpack-11eefeef" start="1501635153225" dump="1501635161694"/><sessioninfo id="s-MacBook-Pro.local-b15a7ee9" start="1502647969911" dump="1502647979776"/></report>
```

**Comment by vanniktech** [comment]
Yup there's definitely something wrong with java projects. I opened #81
