### ISSUE TITLE
Add Kotlin source directories

### ISSUE THREAD

**Issue by kingargyle** [vanniktech/gradle-android-junit-jacoco-plugin#74]
Currently it looks like the plugin is hard coded to expect all source files under either the product flavor/java or src/main/java.   In my project, I have Kotlin and Java files separated.   Is there a way with the plugin to configure it so that this extra directory can be added for a source folder.

In junitExtensions it would be nice to say have:

 coverateSourceDirs = ["src/main/java", "src/main/kotlin"]

**Comment by vanniktech** [comment]
Yup we also got bitten by this in #73.
