### ISSUE TITLE
Generate csv report

### ISSUE THREAD

**Issue by alexrwegener** [vanniktech/gradle-android-junit-jacoco-plugin#93]
Would you be open to generating the csv report in addition to the html and xml reports? Or giving the option to generate via extension? Would be more than willing to open a pr. Thanks!

**Comment by vanniktech** [comment]
Does the gradle plugin offer this?

**Comment by alexrwegener** [comment]
Yep! For example:
```
reports {
  xml.enabled = true
  html.enabled = true
  csv.enabled = true
}
```

**Comment by vanniktech** [comment]
Oh sure then let's add it
