### ISSUE TITLE
Gradle android plugin 3.0.0 failed

### ISSUE THREAD

**Issue by rslama** [vanniktech/gradle-android-junit-jacoco-plugin#99]
After update android gradle plugin to version 3.0.0 build failed with follow error:

Error:Execution failed for task ':app:transformClassesWithFirebasePerformancePluginForDebug'.
> SHA-256 digest error for org/jacoco/agent/rt/RT.class

**Comment by RicardoBelchior** [comment]
+1

**Comment by vanniktech** [comment]
Seems like a Firebase issue.

**Comment by vanniktech** [comment]
I'm pretty sure this is an issue in the firebase performance plugin hence I'm closing this. Feel free to reopen if you think otherwise.
